### ISSUE TITLE
mathjax cannot work

### ISSUE THREAD

**Issue by keltoy** [iissnan/hexo-theme-next#1154]
### Expected behavior (预期行为)

应该显示组合公式
![image](https://cloud.githubusercontent.com/assets/9132005/19019827/2e22b2c4-88c7-11e6-95f1-497161e5361c.png)

### Actual behavior (实际行为)

不能显示正确的公式
$$  C_{n-1}^k = C_{n-1}^{k-1} + C_{n-1}^{k-1} $$
![image](https://cloud.githubusercontent.com/assets/9132005/19019837/5021e99e-88c7-11e6-88ed-f6bff8006497.png)

### Steps to reproduce the behavior (重现步骤)

$$  C_{n-1}^k = C_{n-1}^{k-1} + C_{n-1}^{k-1} $$

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse  ✔
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
Browser: Chrome
System: Mac OS

**Comment by familyld** [comment]
这个问题是由Hexo自带的Markdown渲染引擎和MathJax冲突引起的，解决方法很简单。更换Markdown渲染引擎就可以了。详细可以查看[我的博文](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/)。

This issue is caused by the conflict of hexo-renderer-marked(Hexo's default Markdown renderer) and MathJax. To fix this issue, you can simply change your markdown renderer. See the detail in [my blog](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/).

**Comment by keltoy** [comment]
非常感谢，familyld，解决了我的问题。

Thanks very much, familyld!!

**Comment by BarryLiu1995** [comment]
@familyld 你好，我直接按照你的教程去做，结果发现块状LaTeX式子直接没有了，行内LaTeX还是没有解析出来。之后我就找了其他教程，使用了`npm install hexo-renderer-markdown-it --save`。可是不知道为什么LaTeX是可以解析出来了，但是我的博客首页却出了问题，please check，第一篇[博文](http://barryliu1995.studio/)（使用了LaTeX）直接在首页全文展示出来，
第一次处理
![default](https://user-images.githubusercontent.com/20590350/28449448-ad108ef4-6e12-11e7-977d-db09eb5d10f0.jpg)
第二次处理
![Markdown](http://i4.piimg.com/1949/b671d6e5a19ff694.jpg)
