### ISSUE TITLE
hexo s可以正常浏览，hexo d发布之后，网页一片空白，只有底部的页码能看到。

### ISSUE THREAD

**Issue by zhanglongxiang** [iissnan/hexo-theme-next#1219]
使用的NexT.Mist主题，hexo s可以正常浏览，hexo d发布之后，网页一片空白，只有底部的页码能看到。这是为什么？谢谢！

**Comment by caiyue1993** [comment]
# 1214 已提供解决方案

**Comment by caiyue1993** [comment]
#1214 已提供解决方案

**Comment by Ryancheung91** [comment]
建议看下相关issue，已经有解决办法了。source/vendors文件夹更名为lib，修改主题配置文件对应参数，然后c，g，s一遍看。发自我的iPhone
            在2016年11月04日 08:54，zhanglx 写道:使用的NexT.Mist主题，hexo s可以正常浏览，hexo d发布之后，网页一片空白，只有底部的页码能看到。这是为什么？谢谢！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iissnan/hexo-theme-next","title":"iissnan/hexo-theme-next","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iissnan/hexo-theme-next"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"hexo s可以正常浏览，hexo d发布之后，网页一片空白，只有底部的页码能看到。 (#1219)"}],"action":{"name":"View Issue","url":"https://github.com/iissnan/hexo-theme-next/issues/1219"}}}
