### ISSUE TITLE
相关文章推荐如何实现？

### ISSUE THREAD

**Issue by DavidFnck** [iissnan/hexo-theme-next#1385]
### Expected behavior (预期行为)
能够在每天文章下面显示相关文章，可能依据的是标签或者关键词。

--- 20170228 更新 ---
谢谢作者的建议，但是好像都不是很简单啊。www.davidfnck.com ，一看大段的调整，生怕给整坏了，最好能够直接在 _config 里面添加一下的。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔ Pisces

**Comment by He110te4m** [comment]
同问~

**Comment by iissnan** [comment]
需要 Plugin 的支持，例如 [hexo-related-posts](https://github.com/tea3/hexo-related-popular-posts)，Plugin 本身也需要借助一些第三方服务。

**Comment by imxz** [comment]
前两天写了代码实现，需要的朋友可以参考：

[Hexo相关文章的代码实现](https://ethanblog.com/tech/hexo-related-posts.html)

**Comment by myjeshurun** [comment]
@imxz @iissnan 他们的代码都是在ejs文件中修改的，NexT是swig文件，我加了。却不行。你们能帮我一下吗？再具体告诉我该改哪个文件，我不太懂，谢谢！

**Comment by swordspoet** [comment]
I am wandering if Next could add **related-posts** to its theme, I think it could improve blog's SEO

**Comment by huiwang** [comment]
Hello everyone, I developed a new plugin which generates a list of recommended posts for each post. This list contains both internal and exchanged external links. You can live preview this feature [here](http://hui-wang.info/2017/12/02/%E5%AD%A6%E4%B9%A0%E5%A6%82%E4%BD%95%E5%AD%A6%E4%B9%A0/). 

For more details about the plugin, you can find the doc [here](https://github.com/huiwang/hexo-recommended-posts/blob/master/README-en.md) 

I also opened a PR https://github.com/iissnan/hexo-theme-next/pull/2054

**Comment by huiwang** [comment]
@DavidFnck， @myjeshurun [hexo文章推荐插件](https://github.com/huiwang/hexo-recommended-posts)，可以在零配置的情况下，就能实现文章推荐功能，欢迎试用！

**Comment by ivan-nginx** [comment]
@huiwang as i remember, u say me what u coding just for fun, isn't it?
And as i see for now (and not only for now, exactly), u forced suggest to peoples soft, which maybe steal do some logs / steal something or, i don't know.. what may be. U suggest it to peoples as if **most u** want what peoples use your soft, not for they.
Also, [u cancel offer to test this complexly](https://github.com/iissnan/hexo-theme-next/pull/2054#issuecomment-355068720) and i think smart peoples must asking the questions to u, this is too  much suspiciously, not? 
Confess, your plugin have a virus or not? :smile:

**Comment by huiwang** [comment]
@ivan-nginx i don't get your ideas clearly.

> u forced suggest to peoples soft, which maybe do some logs / steal something or, i don't know.. what may be. U suggest it to peoples as if most u want what peoples use your soft, not for they.

I'm promoting the plugin cause if only few people use it, it makes no sense. I'm not sure this answers your question.

> Also, u cancel offer to test this complexly and i think smart peoples must asking the questions to u, this is too much suspiciously, not?

I welcome all smart people to ask questions. I now have 2 happy users (not 5k) of this plugin and performance is not in my prioity list. Other than performance, I've more important things to improve. 
 
I had lots of fun discussing this plugin with my friends.  Stay tuned !

**Comment by ivan-nginx** [comment]
> I'm promoting the plugin cause if only few people use it, it makes no sense. I'm not sure this answers your question.

Yeah, i see. U coding just for fun, but u `promoting`. This at least strange, no? And u not simple promouting, u just real force this soft. I say it because i see it, and this is true. And to me [u told in pull](https://github.com/iissnan/hexo-theme-next/pull/2054#issuecomment-355068720) what this plugin is good, etc., trying to proof me what it life-needed thing, but it is not true. And @geekrainy explain to u why, right? And u still force to this repo your plugin because u, how u told, — do code for fun, but promoute this.

Of course in my free time i test it, how u said? — for fun. But your behavior looks like fishily, that's what i'm try to say.

Please, do not need spam or flood or how to call it, here. People knows, your links in different topics. Take your time on code, on code for fun, ok? I think it will be more useful, and, mb not only 2 happy users became, and 3-5-7-12 (not 5k, of course).

**Comment by huiwang** [comment]
@ivan-nginx, I think we have different experiences and may see things differently. Code something that nobody uses is not fun at all.

**Comment by ivan-nginx** [comment]
@huiwang hah! Good joke. Code for fun mean — u just coding for fun, for yourself. And u use at least your code by youself. And if other peoples use your code too, it's good, yeah; but promoting — this is i think not for fun, lol. It's exists a work: promotion (e.g. marketing). I don't think what promote falls into «fun» category.

And, yes, as i can see
> we have different experiences and may see things differently

So, again: please, not need to promote here. Because i still enabled e-mail attention on whole repo, because i promised to make smooth NexT rebase to peoples who needed some help. Please, look at your code again and try to do something better — it's will be better promote.

**Comment by huiwang** [comment]
Apparently, we have different definitions on fun. I'm really sorry for the spam cause I didn't know you check all issues here. Thanks for your hard work and kind reminder.
