### ISSUE TITLE
百度分享功能失效 - Next 5.1.0 - Hexo

### ISSUE THREAD

**Issue by jetyu** [iissnan/hexo-theme-next#1592]
### Expected behavior (预期行为)
设置百度分享之后应该出现分享按钮。jiathis可以唉~

### Actual behavior (实际行为)
没有出现分享按钮

### Steps to reproduce the behavior (重现步骤)
已经设置了true了。。。但是deployed到prod没有显示~
https://jetyu.me/
https://jetyu.me/post/muscle-building-meal.html

 
### Other Information (Like Browser, System, Screenshots)
- Next 5.1.0 
- Hexo 最新
PS：jiathis不支持https，百度分享不知道是不是也不支持https啊~

**Comment by Alexander-Chiang** [comment]
百度分享也不支持HTTPS，这里有人通过本地化代码解决了这个问题：https://github.com/hrwhisper/baiduShare

**Comment by ehlxr** [comment]
@Alexander-Chiang 这个不错，网站开启 https 后，所有的分享都有问题，这个正好解决

**Comment by ivan-nginx** [comment]
@jetyu don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
The problem is about Baidu, a search engine similar with Google, this issue is inappropriate to open in this repository.

**Comment by youngjuning** [comment]
@ivan-nginx  My share plugin ，just needmoreshare2 go work

**Comment by youngjuning** [comment]
![2017-10-17_124452](https://user-images.githubusercontent.com/13204332/31647153-03d60316-b339-11e7-9dea-697502d6a80a.png)

**Comment by youngjuning** [comment]
`VM2518:1 A parser-blocking, cross site (i.e. different eTLD+1) script, http://v3.jiathis.com/code/plugin.client.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.`
