### ISSUE TITLE
代码块增加复制功能

### ISSUE THREAD

**Issue by myoss** [iissnan/hexo-theme-next#1684]
### Expected behavior (预期行为)
期望代码块的右上角有一个复制按钮，类似  [http://v3.bootcss.com/css/](http://v3.bootcss.com/css/)

### Actual behavior (实际行为)
目前无

### Steps to reproduce the behavior (重现步骤)
目前无

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔

**Comment by zhuzhuyule** [comment]
just like [**this**](https://zhuzhuyule.xyz/2017/01/10/Hexo%E4%B8%8B%E7%9A%84Markdown%E8%AF%AD%E6%B3%95(GFM)%E5%86%99%E5%8D%9A%E5%AE%A2/#标题) ?

**Comment by myoss** [comment]
是的，如何实现的呢

**Comment by zhuzhuyule** [comment]
i  used the [clipboard.js](https://clipboardjs.com/) !
the github : https://github.com/zenorocha/clipboard.js

**Comment by heliuphy** [comment]
@zhuzhuyule 请问鼠标放到左侧边栏后的动画效果怎么做出来的呀？

**Comment by zhuzhuyule** [comment]
1.头像动画，css 实现
2.背景显示，js 实现
3.时钟，js实现
4.头像背景，canvas+js实现
@heliuphy 尽量本周内把我的代码都贴出来.

**Comment by heliuphy** [comment]
好的，谢谢！

2017-05-31 8:41 GMT+08:00 zhuzhuyule <notifications@github.com>:

**Comment by yafey** [comment]
@zhuzhuyule 关注中

**Comment by bharals** [comment]
@zhuzhuyule 关注中，加油！

**Comment by xkcoding** [comment]
@zhuzhuyule mentioned

**Comment by zhuzhuyule** [comment]
@myoss @heliuphy @Jan9th @yafey @bharals @xkcoding 
复制功能已经写好 ，可以尝试了，有问题给我留言

[HEXO优化之（二）----添加复制功能](https://zhuzhuyule.xyz/2017/06/12/HEXO/HEXO%E4%BC%98%E5%8C%96%E4%B9%8B%EF%BC%88%E4%BA%8C%EF%BC%89-%E6%B7%BB%E5%8A%A0%E5%A4%8D%E5%88%B6%E5%8A%9F%E8%83%BD/)

**Comment by heliuphy** [comment]
赞一个

2017-06-22 0:00 GMT+08:00 zhuzhuyule <notifications@github.com>:

**Comment by heliuphy** [comment]
@zhuzhuyule 没有`\themes\next\layout\_custom\custom.swig`这个文件呀？

**Comment by zhuzhuyule** [comment]
@heliuphy 已经更新。
[更新此处](https://zhuzhuyule.xyz/2017/06/12/HEXO/HEXO%E4%BC%98%E5%8C%96%E4%B9%8B%EF%BC%88%E4%BA%8C%EF%BC%89-%E6%B7%BB%E5%8A%A0%E5%A4%8D%E5%88%B6%E5%8A%9F%E8%83%BD/#插入主题中)

感谢提出问题。

**Comment by heliuphy** [comment]
感谢分享 (＾▽＾) 
发自网易邮箱大师
在2017年06月22日 23:05，zhuzhuyule 写道： @heliuphy 已经更新。
更新此处
感谢提出问题。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iissnan/hexo-theme-next","title":"iissnan/hexo-theme-next","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iissnan/hexo-theme-next"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhuzhuyule in #1684: @heliuphy 已经更新。\r\n[更新此处](https://zhuzhuyule.xyz/2017/06/12/HEXO/HEXO%E4%BC%98%E5%8C%96%E4%B9%8B%EF%BC%88%E4%BA%8C%EF%BC%89-%E6%B7%BB%E5%8A%A0%E5%A4%8D%E5%88%B6%E5%8A%9F%E8%83%BD/#插入主题中)\r\n\r\n感谢提出问题。"}],"action":{"name":"View Issue","url":"https://github.com/iissnan/hexo-theme-next/issues/1684#issuecomment-310408171"}}}

**Comment by ivan-nginx** [comment]
@myoss solved?

**Comment by anson2416** [comment]
这个功能很使用  👍

**Comment by tzy521521** [comment]
我的总是显示不出来复制按钮，和hexo 和next的版本有关系吗？

**Comment by wangxianh** [comment]
一直显示不成功，提示这个错误
Uncaught ReferenceError: Clipboard is not defined
    at createCopyBtns (custom.js:31)
这是什么原因啊？

**Comment by ivan-nginx** [comment]
Feature already implemented in [NexT v6.2.0](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.2.0)

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
