### ISSUE TITLE
The share icon of Hyper Comment is covered by something I don't know

### ISSUE THREAD

**Issue by Gabirel** [iissnan/hexo-theme-next#1721]
### Expected behavior (预期行为)
![image](https://user-images.githubusercontent.com/12933851/27226460-c05a830e-52d1-11e7-85a5-70296df83df7.png)

### Actual behavior (实际行为)
![image](https://user-images.githubusercontent.com/12933851/27226427-90bc20e4-52d1-11e7-9a06-3d882ffbc6fe.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes  ✔
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)

I don't know how your blog make it right. Umm.. not mine @ivan-nginx

**Comment by Gabirel** [comment]
```css
.comments {
  padding: 40px;
}
```

Although it works, it's ugly

**Comment by Gabirel** [comment]
Already fixed. But I don't know how to integrate it into hexo-next-theme without breaking file structure. 

If you don't need this, close it.

**Comment by hiyforever** [comment]
Because of in /themes/next/source/css/_common/components/pages/post-detail.styl, there is:
`.page-post-detail {

  .sidebar-toggle-line { background: $sidebar-highlight; }

  **.comments { overflow: hidden; }**
}`
It hides the scroll for too long contents, including the things you want.

So you should add below in /themes/next/source/css/_custom/custom.styl to override it in high priority.
`.page-post-detail .comments {
    overflow: inherit;
}`

**Comment by Gabirel** [comment]
Thanks for telling me this. It works very well.
