### ISSUE TITLE
In Hexo.Mist , side panel with author name, avatar and social links is not scrollable

### ISSUE THREAD

**Issue by haocen-site** [iissnan/hexo-theme-next#1888]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
- [ ] Latest Master branch.
- [x] Latest Release version.
- [ ] Old version - 
```

**NexT Scheme:**

```
- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini
```

### Other Information 
This is tested with latest v5.1.2, with fresh build Hexo template.

![image](https://user-images.githubusercontent.com/17036053/30599561-e05e9c50-9d2a-11e7-949a-12639d8d4aa1.png)

The side panel with social links, author name, avatar and social links is not scrollable, cause the bottom content get cut off.

**Comment by ivan-nginx** [comment]
Welcome back, @haocen-site, and yep, this is right: in Mist and Muse there is no affix working (and on master branch too). A few days ago i just refactoring sidebar affix in Gemini scheme and also think about Mist | Muse to scrolling down if content is bigger then viewport. U can check it [here](http://test.almostover.ru). Any suggestions about this?

**Comment by Haocen** [comment]
Sorry for the confusion, I was using another GitHub account to host my blog in order to avoid sharing SSH key with automated system.

I propose to fix this problem by give `.siderbar` `overflow-y: auto` css property:
hexo-sidebar-overflow-fix.haocen.org

From what I understand, in order to make `affix.js` work properly, it require the page content to be larger in height than the sidebar?

**Comment by ivan-nginx** [comment]
Actually, `post-details.js` and it's function `initAffix` only used in Pisces / Gemini scheme because there is separated sidebar. Mist / Muse schemes have sidebar from right, so, they can't to show tall content inside without `overflow` and scrolling. Yes, `overflow-y: auto` given on `.site-overview` make scroll to main sidebar overview on Mist and Muse schemes, but it brake vision on Pisces and Gemini. Ok, i post there some screens to look and u always can see it on [test](http://test.almostover.ru/sidebar-tall-toc-test-post/) site.

Mist / Muse with `overflow-y: auto` (**good**):
![image](https://user-images.githubusercontent.com/16944225/30712424-abe75f20-9f14-11e7-9431-4fa2edb451f5.png)

Pisces / Gemini with `overflow-y: auto` (**bad**):
![image](https://user-images.githubusercontent.com/16944225/30712366-795c67e4-9f14-11e7-93bc-0119a3559439.png)

I'm working on it now and on TOC too. There are many conflict switches and some hard to fast resolve. If that was 1 dcheme — fix may be fast and clean. Also, tske a look on `post-details.js` and on this function:
```
    // Initialize TOC Width.
    var scrollbarWidth = NexT.utils.getScrollbarWidth();
    $('.post-toc').css('width', 'calc(100% + ' + scrollbarWidth + 'px)');
    //$('.site-overview').css('width', 'calc(100% + ' + scrollbarWidth + 'px)');
  }
```
This hide scrollbar from vision but still give scroll if sidebar content bigger than viewport.

**Comment by ivan-nginx** [comment]
@Haocen @haocen-site there is fix in **PART 2** #1898 pull. Check it and close issue if resolved.

**Comment by Haocen** [comment]
Sure, I'll check it out now.

**Comment by Haocen** [comment]
Confirmed.

Demo at: http://hexo-sidebar-overflow-fix.haocen.org/ is working as expected.
