### ISSUE TITLE
some categories on "categories/..." path can not be founded(404)?

### ISSUE THREAD

**Issue by coderunner-xinxin** [iissnan/hexo-theme-next#1903]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
it should be the same as this image:
![image](https://user-images.githubusercontent.com/16172530/30840484-22a8f558-a23d-11e7-9312-17bae73d0d03.png)

### Actual behavior 
but actually:
![image](https://user-images.githubusercontent.com/16172530/30840502-45947628-a23d-11e7-9faf-d4be84d6d016.png)

### Steps to reproduce the behavior 
1. http://coderunner-xinxin.github.io/categories/JavaScript/

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
@coderunner-xinxin it's strange because some categories is work, but some is not work.
I don't know what in your source `*.md` files, but as i can see [here](https://github.com/coderunner-xinxin/coderunner-xinxin.github.io/tree/master/categories),
**there is no** `http://coderunner-xinxin.github.io/categories/JavaScript/` directory on your blog — **there is** https://coderunner-xinxin.github.io/categories/Javascript (working)
**and** https://coderunner-xinxin.github.io/categories/JavaScript/page/2/ (working too).

Always remember: linux (instead of Windows, for example) always split **all files/directories** with **case-sensitive**. It mean in same directory can be `JavaScript`, `Javascript` and `javascript` — and all of they will be with exclusive, different pathes.

So, actual trouble with Hexo — we want to use case-sensitive in categories with pretty-fine vision, but it will genereta case-sensitive links of categories/tags too (categories/**J**ava**S**cript/page/) and always create any problems with rendering and SEO.

And there is simple decision what i find and always use:
In main Hexo `_config.yml`:
```yml
filename_case: 1
```
It will not brake case-sensitive in blog vision, but do all categories/tags to lowercase (categories/**j**ava**s**cript/page/).

Hope this help for u. If issue solved, close it please.

**Comment by ivan-nginx** [comment]
#1904.

**Comment by coderunner-xinxin** [comment]
@ivan-nginx I see... You answer has solved the half of my issue. the other half is:

These files have `lowercase` name on my local project:
- in 'public' file:
![image](https://user-images.githubusercontent.com/16172530/30843096-a02380ca-a24c-11e7-96d9-feb0b348275d.png)

- in '.deploy_git' file:
![image](https://user-images.githubusercontent.com/16172530/30843112-b249bfa8-a24c-11e7-89e7-aa9618262a0d.png)

but...they become `uppercase` on my github [click here](https://github.com/coderunner-xinxin/coderunner-xinxin.github.io/tree/master/categories). I am so curious about this change😂!

**Comment by ivan-nginx** [comment]
This is very, very weird. Can u show what in your `*.md` files? And what in main Hexo config too?
And what half of your issue is solved, i don't understand. A want to see your blog again, but it's redirect to `http://coderunner.xin` and not respanse afterthat.

Anyway, this not NexT theme issue, but if u give some more info, we may resolve it and find solution.

**Comment by coderunner-xinxin** [comment]
@ivan-nginx I am trying to use the command `git mv old-file-name new-file-name` to fix this problem. Actually, it works! Every links can be found after I rename them. But at the same time it means that I must use that command to rename those `uppercase` files after I use `hexo d`...Therefore, this is not a right answer of my issues...waiting for you reply😊

**Comment by ivan-nginx** [comment]
> to rename those uppercase files after I use

They must not be uppercase if u set `filename_case: 1`. U also can try to set it to `2` or set manual mappings in cofig: #1904.

**Comment by coderunner-xinxin** [comment]
I think so...because only files on github account are `uppercase`. I'll try! Thanks for your reply💗. I'll close this issue.

**Comment by a1023166946** [comment]
666
