### ISSUE TITLE
Gitment 配置问题

### ISSUE THREAD

**Issue by icearith** [iissnan/hexo-theme-next#1943]
https://github.com/imsun/gitment/issues/46
这个issues 里提到带参数的 URL 和 不带参数的 URL 会被当成不同的网页处理。需要将

id: document.location.href

改成 id:window.location.pathname

**Comment by leviding** [comment]
@icearith  #1944 . Right?

**Comment by icearith** [comment]
@leviding Yes, this can solve most of the issues related to this situation. However, the author mentioned that some of the corner cases has not been solved. I think this solution could work fine :)

**Comment by aimingoo** [comment]
Use 'mint: true' option. ^^.

No recommend do update or fix in the theme, because ‘document.location.href’ is default and recommend from original project. @see https://github.com/imsun/gitment#constructoroptions

So, i update something in Gitmint, i override 'id' with getter/setter. @see https://github.com/aimingoo/gitmint/blob/master/src/gitment.js#L67

And, gitmint cut anchor but save query, because it must support dynamic pages and more. so, maybe you need new 'id' provider in your site. next example from my blog's option:

```javascript
var SHORT_ID = function(url) { return url.replace(/[\?#].*$/, '').replace(/\/((default\|index)\..{1,4})?$/,'').replace(/^.*\/\|.html$/g, '') };
--
var gitment = new Gitmint({
  id: SHORT_ID(location.href),
  ...
```

Good luck.
