### ISSUE TITLE
标题 使用 `something` 会出问题

### ISSUE THREAD

**Issue by Comee** [iissnan/hexo-theme-next#231]
![qq 20150618123614](https://cloud.githubusercontent.com/assets/5416227/8224953/3231aba6-15c1-11e5-9118-e133a86915b6.png)

**Comment by iissnan** [comment]
谢谢反馈

**Comment by Comee** [comment]
这个还没有解决吗？应该可以直接把标签  转义一下  然后去掉 阴影样式

**Comment by ivan-nginx** [comment]
@Comee don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Comee** [comment]
@ivan-nginx when title containing < and >, right outline (sidebar) will not show the content in < and >

**Comment by ivan-nginx** [comment]
We can use inline special characters for use them in direct [markdown syntax](https://daringfireball.net/projects/markdown/syntax), something about:
```
## ## Test `&lt;blocks&gt;` and &lt;tags&gt; and `<blocks>`
```
but this is not good decision for Hexo.

On any special characters we must use [escape character](https://genius.com/3057216) if u want to non-interpretted them by markdown engine.
We also may use [double backtrick](https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-in-markdown) to escape some characters too, but this is another solution.

And i think this is not Next theme bug, because TOC generated by markdown engine or swig engine by Hexo.
