### ISSUE TITLE
swiftype 搜索的替换

### ISSUE THREAD

**Issue by dynaguy1** [iissnan/hexo-theme-next#841]
### Expected behavior (预期行为)

免费使用swiftype 搜索
### Actual behavior (实际行为)

新注册的swiftype用户只有15天试用，然后$299/月。

有没有替代？

**Comment by S-X-ShaX** [comment]
我记得在网上看到过说这个15天试用只是试用收费项目，搜索引擎是免费的，试用期后会发给你一个邮件，只要选择退回免费版即可。

**不过我的网站还没满试用期，到时候看看再说。**

**Comment by Edenharder** [comment]
Hi there,

We’re writing because you signed up for a free trial of Swiftype that expired a week ago. We haven’t heard from you since, so, starting today, we’ve disabled searches using your account. We wanted to let you know because we noticed you still have at least one search engine in your account.

If we don’t hear from you, then, in another week we’ll remove your data and account from Swiftype. If you’d like to keep this data or continue using Swiftype, please contact our sales team right away and they’ll be happy to help.

Thanks!
Swiftype Support

**Comment by jerrybendy** [comment]
现在似乎是没有免费版了，我的也是过了试用期了，登录进去之后无论点哪个链接都只能跳转到要求付费的页面。

目前还没有找到好的搜索解决方案，空白中。。。

**Comment by BenjaminXi** [comment]
之前也用过swiftype，后来就收费了，听说Algolia不错，可以一试

**Comment by zrdsj** [comment]
我的也是，准备换了。。。真的没那么多钱。。。2333

**Comment by iissnan** [comment]
可以使用 Algolia，配置文档：http://theme-next.iissnan.com/third-party-services.html#algolia-search

**Comment by alanhg** [comment]
swiftype比Algolia确实速度快，目前的主观感受
