### ISSUE TITLE
阅读统计有点问题

### ISSUE THREAD

**Issue by wozien** [iissnan/hexo-theme-next#994]
### Expected behavior (预期行为)

点击进入博客标题，进入博客详细内容阅读数对应加1，刷新首页页面阅读数不变
### Actual behavior (实际行为)

刷新首页，阅读数也会加1
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by zeekyguo** [comment]
是不是只有一篇文章呢？

**Comment by njafei** [comment]
我也遇到了同样的问题，阅读统计不对，但是后台看leancloud的信息是有的，在首页展示都是0，而在具体的每篇文章的页面，都没有显示，直接展示 ‘阅读次数’

**Comment by ivan-nginx** [comment]
@wozien dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by conupefox** [comment]
@ivan-nginx 

I have the same issue.


translation

Expected behavior (预期行为)

点击进入博客标题，进入博客详细内容阅读数对应加1，刷新首页阅读数不变
Click into the posts title, number of views plus 1.
Refresh the home page, number of views will not increased.

Actual behavior (实际行为)

刷新首页，阅读数也会加1
Refresh the home page, number of views will plus 1


NexT Version:  v5.1.2

**Comment by ivan-nginx** [comment]
@conupefox can u show live demo with this bug?

**Comment by conupefox** [comment]
@ivan-nginx 

http://blog.d2okkk.net/

**Comment by ivan-nginx** [comment]
0. http://blog.d2okkk.net/
1. Click into the posts title, number of views: 28.
2. Refresh the **home page**, number of views will **increased**: 29.
3. Click into the posts title, number of views: 30.
4. Refresh the **page**, number of views will **increased**: 31.

Google Chrome, cache enabled.
